# Generated by Django 5.1.15 on 2026-09-07 04:26

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('meaning', models.CharField(default='', max_length=255)),
                ('part_of_speech', models.CharField(blank=True, max_length=50, null=True)),
                ('pronunciation', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(help_text='Mô tả ý nghĩa bằng tiếng Anh')),
                ('examples', models.JSONField(default=list, help_text='Danh sách các câu ví dụ')),
                ('audio_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'vocabulary',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('USER', 'Người dùng'), ('MODERATOR', 'Kiểm duyệt viên'), ('ADMIN', 'Admin')], default='USER', max_length=20)),
                ('total_score', models.IntegerField(default=0)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AIChatSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aichatsession',
            },
        ),
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('USER', 'Người dùng'), ('AI', 'Trợ lý AI')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='elearningapp_api.aichatsession')),
            ],
            options={
                'db_table': 'aichatmessage',
            },
        ),
        migrations.CreateModel(
            name='CommunityGameLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('game_type', models.CharField(choices=[('QUIZ', 'Trắc nghiệm'), ('GUESS', 'Đoán từ vựng'), ('SORT', 'Sắp xếp từ')], max_length=20)),
                ('difficulty', models.CharField(choices=[('EASY', 'Dễ'), ('MEDIUM', 'Vừa'), ('HARD', 'Khó')], default='MEDIUM', max_length=20)),
                ('base_score', models.IntegerField(default=100)),
                ('time_limit', models.IntegerField(blank=True, help_text='Giới hạn thời gian (giây)', null=True)),
                ('game_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('play_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PRIVATE', 'Riêng tư'), ('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối')], default='PRIVATE', max_length=20)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, db_table='communitygamelevel_likes', related_name='liked_community_levels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'communitygamelevel',
            },
        ),
        migrations.CreateModel(
            name='FlashcardDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('difficulty', models.CharField(choices=[('EASY', 'Dễ'), ('MEDIUM', 'Vừa'), ('HARD', 'Khó')], default='MEDIUM', max_length=20)),
                ('learner_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(limit_choices_to={'role': 'MODERATOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_decks', to=settings.AUTH_USER_MODEL)),
                ('vocabularies', models.ManyToManyField(blank=True, db_table='flashcarddeck_vocabularies', related_name='decks', to='elearningapp_api.vocabulary')),
            ],
            options={
                'db_table': 'flashcarddeck',
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, db_table='forumpost_likes', related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forumpost',
            },
        ),
        migrations.CreateModel(
            name='ForumComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='elearningapp_api.forumpost')),
            ],
            options={
                'db_table': 'forumcomment',
            },
        ),
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('score_earned', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gamehistory',
            },
        ),
        migrations.CreateModel(
            name='SystemGameLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('game_type', models.CharField(choices=[('QUIZ', 'Trắc nghiệm'), ('GUESS', 'Đoán từ vựng'), ('SORT', 'Sắp xếp từ')], max_length=20)),
                ('difficulty', models.CharField(choices=[('EASY', 'Dễ'), ('MEDIUM', 'Vừa'), ('HARD', 'Khó')], default='MEDIUM', max_length=20)),
                ('base_score', models.IntegerField(default=100)),
                ('time_limit', models.IntegerField(blank=True, help_text='Giới hạn thời gian (giây)', null=True)),
                ('game_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('play_count', models.IntegerField(default=0)),
                ('sequence_number', models.IntegerField(default=0, help_text='Thứ tự màn chơi')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'systemgamelevel',
            },
        ),
        migrations.CreateModel(
            name='UserActiveDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearningapp_api.flashcarddeck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_decks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'useractivedeck',
                'unique_together': {('user', 'deck')},
            },
        ),
    ]
